version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - ./.db.env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    image: frcgustavo/blogging-api:0.0.0
    env_file:
     - ./.api.env
    depends_on:
      - db
    ports:
      - 5000:5000
volumes:
  dbdata:
