version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
  api:
    build:
      context: ./
      dockerfile: dockerfile
    env_file:
     - ./.env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
    ports:
      - 5000:5000
    command: yarn run dev
volumes:
  dbdata:
