version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - ./.db.env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  mongodb:
    image : mongo
    env_file:
     - ./.mongo.env
    volumes:
      - type: volume
        source: mongodbdata
        target: /data/db
    ports:
      - 27017:27017
  api:
    image: frcgustavo/blogging-api:0.1.0
    env_file:
     - ./.api.env
    depends_on:
      - db
    ports:
      - 5000:5000
volumes:
  dbdata:
  mongodbdata:
