version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build:
      context: ./
      dockerfile: dockerfile
    env_file:
     - ./.env
    depends_on:
      - db
    ports:
      - 5000:5000
volumes:
  dbdata:
