version: '3.8'

services:
  db:
    image: 'postgres:14'
    env_file:
      - ./.db.env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.pgadmin.env
    ports:
      - 5050:80
  mongodb:
    image : mongo
    env_file:
     - ./.mongo.env
    volumes:
      - type: volume
        source: mongodbdata
        target: /data/db
    ports:
      - 27017:27017
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
     - ./.api.env
    depends_on:
      - db
      - mongodb
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
    ports:
      - 5000:5000
    command: yarn run dev  
volumes:
  dbdata:
  mongodbdata: