version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - ./.db.env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.pgadmin.env
    ports:
      - 5050:80
  api:
    image: frcgustavo/blogging-api:0.0.0
    env_file:
     - ./.api.env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
    ports:
      - 5000:5000
    command: yarn run dev  
volumes:
  dbdata:
